name: 'Terraform'

on:
  push:
    branches: [ "main" ]

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_TENANT_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_TEANANT_ID}}
  ROOT_PATH: '${{github.workspace}}/terraform'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PSP }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{env.ROOT_PATH}}

    - name: Terraform Format
      run: terraform fmt
      working-directory: ${{env.ROOT_PATH}}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{env.ROOT_PATH}}

    - name: Terraform Apply
      if: success()
      run: terraform apply -auto-approve
      working-directory: ${{env.ROOT_PATH}}
