name: 'Terraform'

on:
  push:
    branches: [ "main" ]

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_TENANT_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_TEANANT_ID}}
  ROOT_PATH: '${{github.workspace}}/terraform'

 run: |
          cd ${{ github.workspace }}/terraform
          terraform init --upgrade
          terraform plan
          terraform apply -auto-approve
